(function(root){
'use strict';const D=typeof module!=='undefined'&&module.exports?require('./data.js'):root.BloomData;
const themes={knight:['絢爛','慈愛'],witch:['天極','星詠'],alchemist:['猛毒','万華'],dragoon:['覇竜','焔心'],ranger:['月牙','幻舞'],all:['剛華','流転']};
D.upgradeLevel=c=>c.branch?2:c.upgraded?1:0;
D.branches=(id,hero)=>{const c=D.cards[id];if(!c||['curse','status'].includes(c.type))return {};const e={...c.effects,...c.upgrade},cost=e.cost??c.cost,names=themes[c.hero==='all'&&['strike','guard'].includes(id)?hero:c.hero]||themes.all,p={},t={};if(e.damage)p.damage=e.damage+Math.max(3,Math.ceil(e.damage*.35));else for(const k of ['block','heal','poison','frost','bloom','strength','dexterity','thorns','regen','bloomTurn','drawTurn','energyTurn','blockTurn','poisonTurn','heat','heatTurn','draw','energy','weak','vulnerable'])if(e[k])p[k]=e[k]+Math.max(1,Math.ceil(e[k]*.35));if(!Object.keys(p).length)p.block=(e.block||0)+8;if(cost>=2)t.cost=cost-1;else if(cost===1){t.draw=(e.draw||0)+1;t.block=(e.block||0)+3;}else t.block=(e.block||0)+5;
const special={dragonfang:[{hits:3},{damage:22,hits:1,heatScale:4,consumeHeat:true}],catalyst:[{poisonMultiply:(e.poisonMultiply||3)+1},{cost:0,exhaust:true}],doublecut:[{hits:3},{bloom:2,draw:1}],shatter:[{frostScale:(e.frostScale||2)+2},{cost:Math.max(0,cost-1)}],moonfang:[{comboScale:(e.comboScale||2)+2},{cost:0,draw:1}],strike:[{damage:(e.damage||9)+5},{damage:e.damage,draw:1}],guard:[{block:(e.block||8)+6},{cost:0,block:e.block}],finalbloom:[{bloomScale:(e.bloomScale||2)+3},{cost:Math.max(1,cost-1),block:14}],crimsonlance:[{heatScale:(e.heatScale||2)+2},{cost:Math.max(1,cost-1),heat:5}],silverwaltz:[{hits:(e.hits||3)+2},{cost:Math.max(1,cost-1),draw:2}],moonstep:[{block:16},{draw:3,block:11}],recycle:[{block:16},{draw:3,block:11}],warmth:[{block:16},{draw:3,block:11}]};return {power:{id:'power',name:names[0],subtitle:'威力・主効果を極める',effects:special[id]?.[0]||p},technique:{id:'technique',name:names[1],subtitle:'手数・戦術を広げる',effects:special[id]?.[1]||t}};};
Object.assign(D.relics,{
rosegrail:{name:'薔薇の聖杯',icon:'cup',hero:'knight',desc:'カードで開花を得るたび、得た開花の2倍のブロックを得る。'},petalseal:{name:'花聖の紋章',icon:'flower',hero:'knight',desc:'毎ターン最初のアタックは、開花5以上なら敵全体を対象にする。'},frostbell:{name:'氷月の鈴',icon:'bell',hero:'witch',desc:'カードで敵に氷結を与えるたび、3ブロック。カード1枚につき1回。'},moonquill:{name:'星詠みの羽根',icon:'feather',hero:'witch',desc:'毎ターン最初のスキル使用後、カードを1枚引く。'},amberflask:{name:'琥珀の蒸留瓶',icon:'potion',hero:'alchemist',desc:'毎ターン最初に毒を付与するカードは、対象にさらに毒2。'},rootretort:{name:'根の調合炉',icon:'leaf',hero:'alchemist',desc:'ターン終了時、生きている毒状態の敵がいれば4ブロック。'},sunemblem:{name:'太陽竜の勲章',icon:'flame',hero:'dragoon',desc:'毎ターン最初のアタックは、灼熱6以上なら敵全体を対象にする。'},embercore:{name:'不滅の火種',icon:'crystal',hero:'dragoon',desc:'毎ターン最初のアタックで灼熱が1減らなくなる。灼熱の全消費は防げない。'},silvermetronome:{name:'銀狼の拍子',icon:'moon',hero:'ranger',desc:'1ターン中、カードを3枚使うごとに1枚引き、エナジー1を得る。'},moonpin:{name:'双月の髪飾り',icon:'star',hero:'ranger',desc:'毎ターン1回、連携2以上で使うアタックの攻撃回数が1増える。'}});
const A=(damage,hits=1)=>({kind:'attack',damage,hits}),B=strength=>({kind:'buff',strength}),S=block=>({kind:'defend',block}),M=(damage,status,amount)=>({kind:'debuff',damage,status,amount});
Object.assign(D.enemies,{crystalguard:{name:'星晶の護衛',sprite:16,hp:34,pattern:[S(5),A(6)]},sunseed:{name:'日輪の種',sprite:17,hp:56,pattern:[A(7,2),S(14),B(2)]},cloudfox:{name:'雲わたりの狐',sprite:18,hp:58,pattern:[A(8,2),M(9,'weak',1),A(19)]},clockowl:{name:'ぜんまいフクロウ',sprite:19,hp:62,pattern:[S(16),A(9,2),B(2)]},cometling:{name:'流星の精',sprite:20,hp:60,pattern:[M(10,'dazed',1),A(7,3),S(10)]},zodiacknight:{name:'黄道の騎士',sprite:21,hp:85,pattern:[S(20),A(22),A(10,2)]},eliteStorm:{name:'嵐を織る狐',sprite:18,hp:120,elite:true,pattern:[B(2),A(8,3),M(18,'vulnerable',1)]},eliteZodiac:{name:'黄道の近衛',sprite:21,hp:145,elite:true,pattern:[S(22),A(10,3),B(3),A(30)]},bossGriffin:{name:'蒼嵐のグリフィア',sprite:14,hp:390,boss:true,phase:'天を裂く翼',pattern:[A(12,2),A(36)]},bossAurora:{name:'暁光竜ソレイユ',sprite:15,hp:510,boss:true,phase:'めぐる日と月',pattern:[A(13,2),A(38)]}});
D.acts.push({name:'極光の天城',en:'THE AURORA CITADEL',boss:'bossGriffin',theme:'aurora',line:'嵐の先に、星の階段。',normal:[['cloudfox','crystalguard'],['clockowl','bat2'],['cometling','slime2'],['cloudfox','clockowl']],elite:['eliteStorm','eliteDragon']},{name:'暁の聖域',en:'THE SUNHEART SANCTUARY',boss:'bossAurora',theme:'sunheart',line:'小さな勇気が、朝をひらく。',normal:[['zodiacknight','sunseed'],['cometling','clockowl'],['sunseed','cloudfox'],['zodiacknight','crystalguard']],elite:['eliteZodiac','eliteStorm']});D.actFor=i=>D.acts[i%D.acts.length];D.events.find(e=>e.id==='library').options[0].detail='未強化のカードをランダムに2枚、＋に強化';if(typeof module!=='undefined'&&module.exports)module.exports=D;
})(typeof window!=='undefined'?window:globalThis);
