(function(root){
'use strict';
const node=typeof module!=='undefined'&&module.exports,Engine=node?require('./engine.js'):root.BloomEngine,P=node?require('./progression.js'):root.BloomProgress,D=node?require('./expansion-data.js'):root.BloomData;
const KEY='bloom-spire.save.v2',BACKUP=KEY+'.backup',LEGACY={run:'bloom-spire.run.v1',progress:'bloom-spire.progress.v1',history:'bloom-spire.history.v1',settings:'bloom-spire.settings.v1'};
const clone=v=>JSON.parse(JSON.stringify(v));
function settings(raw={},defaults={}){raw=raw&&typeof raw==='object'?raw:{};const out={music:true,sound:true,motion:true,volume:.35,...defaults};for(const k of ['music','sound','motion'])if(typeof raw[k]==='boolean')out[k]=raw[k];if(Number.isFinite(raw.volume))out.volume=Math.max(0,Math.min(1,raw.volume));return out;}
function history(raw){return (Array.isArray(raw)?raw:[]).filter(s=>s&&Object.hasOwn(D.heroes,s.hero)&&Object.hasOwn(Engine.DIFFICULTIES,s.difficulty)&&Number.isFinite(s.startedAt)&&Number.isInteger(s.act)&&s.act>=0&&s.stats&&Number.isFinite(s.stats.floors)&&Number.isFinite(s.stats.battles)).slice(0,20).map(clone);}
function snapshot(input={},defaults={}){const run=input.run?new Engine(input.run).s:null;if(run)delete run.progress;const records=history(input.history);let progress=P.normalize(input.progress);for(const s of records)progress=P.record(progress,s);if(run)progress=P.record(progress,run);return {format:'BloomSpire',version:2,savedAt:Number.isFinite(input.savedAt)?input.savedAt:Date.now(),run,progress,history:records,settings:settings(input.settings,defaults)};}
function decode(text,defaults={}){const raw=typeof text==='string'?JSON.parse(text):text;if(!raw||typeof raw!=='object')throw new Error('この記録は読み込めません。');if(raw.format==='BloomSpire'){if(raw.version!==2||!Object.hasOwn(raw,'run')||!raw.progress||!Array.isArray(raw.history)||!raw.settings)throw new Error('対応していない記録形式です。');return snapshot(raw,defaults);}const run=new Engine(raw).s;return snapshot({run,progress:raw.progress,history:run.screen==='result'?[run]:[],settings:defaults},defaults);}
function load(storage,defaults={}){const empty=snapshot({},defaults);let damaged=false;try{if(!storage)return {data:empty,status:'unavailable'};for(const key of [KEY,BACKUP]){const raw=storage.getItem(key);if(raw===null)continue;try{return {data:decode(raw,defaults),status:key===KEY?'loaded':'recovered'};}catch{damaged=true;}}
 const input={};let found=false;for(const [field,key] of Object.entries(LEGACY)){const raw=storage.getItem(key);if(raw===null)continue;found=true;try{input[field]=JSON.parse(raw);}catch{damaged=true;}}
 if(input.run)try{input.run=new Engine(input.run).s;}catch{delete input.run;damaged=true;}if(found)return {data:snapshot(input,defaults),status:damaged?'recovered':'migrated'};return {data:empty,status:damaged?'damaged':'empty'};
}catch{return {data:empty,status:'unavailable'};}}
function persist(storage,input){let data;try{data=snapshot({...input,savedAt:Date.now()});}catch(error){return {ok:false,error};}if(!storage)return {ok:false,data,error:new Error('自動保存を利用できません。')};const text=JSON.stringify(data);let old=null,backupOK=false;try{const raw=storage.getItem(KEY);if(raw){decode(raw);old=raw;}}catch{}
 if(old)try{storage.setItem(BACKUP,old);backupOK=true;}catch{}try{storage.setItem(KEY,text);}catch(error){return {ok:false,data,error};}if(!old)try{storage.setItem(BACKUP,text);backupOK=true;}catch{}return {ok:true,backupOK,data};}
function mergeImport(current,incoming,{legacy=false,includeProgress=true}={}){const merged=snapshot(incoming);merged.progress=P.merge(current.progress,incoming.progress,includeProgress);if(legacy)merged.settings=settings(current.settings);const records=history([...incoming.history,...current.history].sort((a,b)=>b.startedAt-a.startedAt));merged.history=records.filter((s,i,a)=>a.findIndex(x=>x.startedAt===s.startedAt&&x.hero===s.hero)===i);return snapshot(merged);}
const api={KEY,BACKUP,LEGACY,settings,history,snapshot,decode,load,persist,mergeImport};if(node)module.exports=api;else root.BloomSave=api;
})(typeof window!=='undefined'?window:globalThis);
